name: Auto-merge konflux PRs

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  merge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}
      - name: merge PRs
        run: python .github/scripts/auto_merge.py --label "ok-to-merge"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#      - name: Approve a PR
#        run: gh pr review --approve "$PR_URL"
#        env:
#          PR_URL: ${{github.event.pull_request.html_url}}
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      - name: Enable auto-merge for Konflux PRs
#        run: gh pr merge --auto --rebase "$PR_URL"
#        env:
#          PR_URL: ${{github.event.pull_request.html_url}}
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}



