name: Combine nudge PRs into one

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  combine-nudges:
    runs-on: ubuntu-latest
    #if: ${{ github.actor == 'red-hat-konflux[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Install oc
        if: ${{ !contains(inputs.label, 'k8s') }}
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Authenticate and set context
        if: ${{ !contains(inputs.label, 'k8s') }}
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_USER: kubeadmin
        with:
          openshift_server_url: ${{ inputs.ocp_host_url }}
          openshift_username: ${{ env.OPENSHIFT_USER }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true

      - name: combine PRs
        run: python ./.github/scripts/combine_nudges.py --pr ${{ github.event.number }} --config nudges_new.yaml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}

